import type { Metadata } from 'next'
import styles from '../legal.module.css'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms governing use of the Telos AI website and client portal.',
  robots: { index: false, follow: false },
}

export default function TermsPage() {
  return (
    <div className={styles.page}>
      <div className={`container ${styles.inner}`}>
        <h1 className={styles.title}>Terms of Service</h1>
        <p className={styles.meta}>Last updated: 31 May 2026</p>

        <h2 className={styles.h2}>1. Who we are and what these terms cover</h2>
        <p>These terms govern your use of the Telos AI website at telosai.co.uk and the associated client portal. Telos AI is the trading name of William Robert Gouldsmith, a sole trader based in England.</p>
        <p>By accessing or using this website, you agree to these terms. If you do not agree, please do not use the site.</p>

        <h2 className={styles.h2}>2. Using this website</h2>
        <p>You may use this website for its intended purposes: learning about our services, making enquiries, booking consultations, and, if you are a client, accessing your portal.</p>
        <p>You must not:</p>
        <ul className={styles.list}>
          <li>Use this website for any unlawful purpose</li>
          <li>Attempt to gain unauthorised access to any part of the site or its infrastructure</li>
          <li>Introduce viruses, malware, or harmful code</li>
          <li>Reproduce, redistribute, or commercially exploit any content from this site without our written permission</li>
          <li>Misrepresent your identity or affiliation when making an enquiry or creating an account</li>
        </ul>
        <p>We reserve the right to suspend or restrict access to the website or portal for anyone who breaches these terms or behaves in a way that is harmful, dishonest, or disruptive.</p>

        <h2 className={styles.h2}>3. The client portal</h2>
        <p>Access to the client portal is available to businesses that have entered into a Client Services Agreement with us. Portal accounts are personal to the individual and business they are created for. You are responsible for keeping your login credentials secure. Notify us immediately at william.gouldsmith@telosai.co.uk if you suspect your account has been compromised.</p>
        <p>The data and reports shown in your portal reflect information we have entered or that has been captured by the systems we have built for you. We will always take reasonable care to ensure the data is accurate, but you should not rely on it for regulated financial, medical, legal, or other professional decisions without independent verification.</p>

        <h2 className={styles.h2}>4. Information on this website</h2>
        <p>The content on this website is for general information purposes only. It does not constitute professional advice of any kind. We describe our services honestly, but we do not guarantee that any outcome, metric, or result described is typical or achievable for any specific business.</p>
        <p>We do not guarantee that the website will always be available, free from errors, or uninterrupted.</p>

        <h2 className={styles.h2}>5. Artificial intelligence</h2>
        <p>Our services involve the use of third-party AI tools and language models. Information generated by AI systems can contain errors, inaccuracies, or unexpected outputs. Nothing on this website or in any AI-generated output provided through our services should be treated as guaranteed, verified, or professional advice. See our Client Services Agreement for the specific terms governing AI outputs delivered as part of a paid engagement.</p>

        <h2 className={styles.h2}>6. Intellectual property</h2>
        <p>All content on this website, including text, graphics, design, and code, is owned by or licensed to William Robert Gouldsmith trading as Telos AI, and is protected by UK and international intellectual property law.</p>
        <p>You may share links to pages on this website. You may not copy, reproduce, adapt, or republish substantial portions of our content without our prior written consent.</p>

        <h2 className={styles.h2}>7. Links to other websites</h2>
        <p>Our website may contain links to third-party websites. These links are provided for convenience only. We are not responsible for the content, accuracy, or privacy practices of any linked site, and linking to a site does not imply endorsement.</p>

        <h2 className={styles.h2}>8. Our liability</h2>
        <p>To the fullest extent permitted by law, we exclude liability for:</p>
        <ul className={styles.list}>
          <li>Any indirect, consequential, or special losses arising from your use of this website</li>
          <li>Losses arising from your reliance on any information on this website</li>
          <li>Interruption or unavailability of the website</li>
          <li>Any loss or damage caused by viruses or harmful material that may infect your device through use of this site</li>
        </ul>
        <p>Nothing in these terms limits our liability for death or personal injury caused by our negligence, fraud or fraudulent misrepresentation, or any other matter that cannot be excluded by law.</p>

        <h2 className={styles.h2}>9. Changes to these terms</h2>
        <p>We may update these terms at any time. The current version is always published on this page with the updated date shown at the top. Your continued use of the website after a change constitutes acceptance of the updated terms.</p>

        <h2 className={styles.h2}>10. Governing law</h2>
        <p>These terms are governed by the law of England and Wales. Any dispute arising in connection with them is subject to the exclusive jurisdiction of the courts of England and Wales.</p>

        <h2 className={styles.h2}>11. Contact</h2>
        <p>William Robert Gouldsmith, trading as Telos AI</p>
        <p>Email: william.gouldsmith@telosai.co.uk</p>
        <p>Address: Bristol, United Kingdom (full postal address available on request)</p>
      </div>
    </div>
  )
}
